#include <random>
#include <iostream>
#include <vector>
#include <algorithm>
#include <chrono>

const int kValueRange = 5000000;
const int kArraySize = 100000;

void print_vector(const std::vector<int>& v) {
    for (auto& i : v)
        std::cout << i << ' ';
    std::cout << '\n';
}

void comb_sort(std::vector<int>& v) {
    int n = v.size();
    int step = n, j, k;
    while ((step = int(step/1.3)) > 1)
        for (j = n-1; j >= step; j--) {
            k = j-step;
            if (v[j] < v[k])
                std::swap(v[j],v[k]);
        }

    bool again = true;
    for (int i = 0; i < n-1 && again; i++)
        for (j = n-1, again = false; j > i; --j)
        if (v[j] < v[j-1]) {
            std::swap(v[j],v[j-1]);
            again = true;
        }
}

int main()
{
    std::random_device rd;  //Will be used to obtain a seed for the random number engine
    std::mt19937 gen(rd()); //Standard mersenne_twister_engine seeded with rd()
    std::uniform_int_distribution<> dis(1, kValueRange);
 
    std::vector<int> v(kArraySize);
    for (auto& i : v) {
        //Use dis to transform the random unsigned int generated by gen into an int in [1, 1,000]
        i = dis(gen);
    }

    // print_vector(v);
    
    auto start = std::chrono::system_clock::now();
    comb_sort(v);
    auto end = std::chrono::system_clock::now();

    // print_vector(v);

    auto elapsed_seconds = end-start;
    std::cout << "elapsed time: " << elapsed_seconds.count() << "us\n";
}